logging:
  level:
    ROOT: INFO
 
eureka:
  instance:
    client:
      serviceUrl:
        defaultzone: http://localhost:8761/eureka/
  metadataMap:
    instanceId: applicationname:${spring.application.instance_id:${local.server.port}}






   
applicationymlfoo: defaultbar
---
spring:
  profiles: cloud
applicationymlfoo: cloud-bar
---
spring:
  profiles: ms
applicationymlfoo: ms-bar