logging:
  level:
    ROOT: INFO
    com.netflix.discovery: DEBUG
 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:55555/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}






   
applicationymlfoo: defaultbar
---
spring:
  profiles: cloud
applicationymlfoo: cloud-bar
---
spring:
  profiles: ms
applicationymlfoo: ms-bar