logging:
  level:
    ROOT: DEBUG
 








   
applicationymlfoo: defaultbar
---
spring:
  profiles: cloud
applicationymlfoo: cloud-bar
---
spring:
  profiles: ms
applicationymlfoo: ms-bar