logging:
  level:
    ROOT: INFO
    com.spring.cloud.ref: DEBUG
management:
  context-path: /admin 
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:55555/eureka/
  instance:
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    hostname: localhost
security:
  oauth2:
    resource:
      load-balanced: true
      userInfoUri: http://auth-server/uaa/user
    client:
      client-id: ${spring.application.name}
hystrix:
  shareSecurityContext: true
  command:
    default:
      execution:
        isolation:
          strategy: SEMAPHORE
feign:
  hystrix:
    enabled: true

  
---
spring:
  profiles: cloud
applicationymlfoo: cloud-bar
---
spring:
  profiles: ms
applicationymlfoo: ms-bar