logging:
  level:
    ROOT: INFO
    com.netflix.discovery: DEBUG
 
eureka:
  instance:
    client:
      serviceUrl:
        defaultzone: http://localhost:55555/eureka/
    instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}






   
applicationymlfoo: defaultbar
---
spring:
  profiles: cloud
applicationymlfoo: cloud-bar
---
spring:
  profiles: ms
applicationymlfoo: ms-bar